// AUTO-GENERATED by scripts/generate-api-tests.ts — do not edit manually
// Write endpoints are skipped by default to avoid mutating live data.
// Enable individual tests in tests/api/manual/ for safe integration cases.
import { describe, it, expect } from "vitest";
import { createTestClient } from "../lib/testClient";
import { getAuthHeaders } from "../lib/auth";

describe("API integration tests (write endpoints)", () => {
  it.skip('POST /admin/auth/login (services/auth.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.post('/admin/auth/login', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('PATCH ${ENDPOINT.BUSINESSES.ADMIN_LIST}/${businessId}/activate (services/businesses.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.patch('${ENDPOINT.BUSINESSES.ADMIN_LIST}/${businessId}/activate', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('PATCH ${ENDPOINT.BUSINESSES.ADMIN_LIST}/${businessId}/suspend (services/businesses.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.patch('${ENDPOINT.BUSINESSES.ADMIN_LIST}/${businessId}/suspend', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });
});
