// AUTO-GENERATED by scripts/generate-api-tests.ts — do not edit manually
import { describe, it, expect, beforeAll } from "vitest";
import { createTestClient } from "../lib/testClient";
import { getAuthHeaders } from "../lib/auth";

describe("API smoke tests (GET)", () => {
  beforeAll(async () => {
    await getAuthHeaders();
  });

  it('GET /admin/revenue/overview returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/admin/revenue/overview');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /admin/revenue/trend returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/admin/revenue/trend');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /brands returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/brands');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /categories returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/categories');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /expense-categories/active returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/expense-categories/active');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /reports/annual returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/reports/annual');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /reports/customers returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/reports/customers');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /reports/expenses returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/reports/expenses');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /reports/inventory returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/reports/inventory');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /reports/profit-loss returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/reports/profit-loss');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /reports/purchases returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/reports/purchases');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /reports/sales returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/reports/sales');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /reports/sold-stock returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/reports/sold-stock');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /reports/stock-history returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/reports/stock-history');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /reports/tax returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/reports/tax');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /users/profile returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/users/profile');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });
});
